### PR TITLE
Fix some issues with unforeseen CSS declarations.

### PR DESCRIPTION
**Pull request by colons**
Declarations including colons would not work at all, and declarations with non-ascii characters wouldn't work on Python 2.

### CODE REVIEW

**Comment by LegoStormtroopr** [comment]
Thanks very much for doing this, however I am going to have to decline this PR.

I made a decision early on to make this library exclusively Python 3 and this means importing `six` would break that intent. Sorry for not having this described clearer.

With regards to the multiple colons in style declarations, can you describe where this is used? I'm guessing for weird (or nested) pseudo-selectors?

**Comment by colons** [comment]
Declarations with colons can appear in, for instance, `content:` declarations, or anywhere URLs appear (like background images, for instance, which is where I was running into it). The CSS parser you're using is fine with them, it was only this custom reassembly that was proving to be an issue.

I understand not wanting to put effort into supporting old releases, but this issue with encoding those strings is the only issue I've run across on Python 2; everything else works perfectly. Now that Python 3 supports (or, i suppose, ignores) `u''`-style strings, would using that be better than importing six? If not, I feel like it'd honestly be preferable for you to throw up an exception when `setup.py` is run under Python 2, because at least then we'd know you expected it not to work.

For the record, the non-ascii characters that were causing the problems were Font Awesome content characters.

**Comment by LegoStormtroopr** [comment]
Hi,

Sorry but I'm going to close this PR now. I appreciate the effort, but I won't be merging in code that adds in Python 2 support. Python 2 support is being dropped for other libraries, and I see no reason to add it here.

If you want to re-open a PR that addresses the colon issue, I'll accept it as quickly as I can, otherwise I'll try and do it myself.

**Comment by colons** [comment]
You could just graft https://github.com/data61/wcag-zoo/pull/6/commits/c53646c95b4602e91ec33857873b30f1a652e75a onto your branch and that'd sort the issue with colons in declarations, or you could merge #7.

**Pull request closed without merging**
